# Generated by Django 5.1.5 on 2025-05-28 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('inn', models.CharField(max_length=10, unique=True, verbose_name='ИНН')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(max_length=100, unique=True, verbose_name='ID операции')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('document_number', models.CharField(max_length=60, verbose_name='Номер документа')),
                ('document_date', models.DateTimeField(verbose_name='Дата документа')),
                ('payer_inn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.organizationsmodel', verbose_name='Организация')),
            ],
        ),
    ]
